NatalCare_System/Controllers/BillingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NatalCare.DataAccess.Interfaces;
using NatalCare.Models.DTOs.VM;
using NatalCare.Models.Entities;

namespace NatalCare_System.Controllers
{
    [Authorize]
    public class BillingController : BaseController<BillingController>
    {

        private readonly IBillingServices _billing;
        private readonly ISelectListServices selectListServices;

        public BillingController(IBillingServices billing, ISelectListServices selectListServices, IModuleAccessServices moduleAccessServices) 
            : base(moduleAccessServices)
        {
            _billing = billing;
            this.selectListServices = selectListServices;
        }


        public async Task<IActionResult> Index()
        {
            if (!await CheckAccessAsync(7)) 
            {
                return RedirectTo();
            }

            return View();
        }

        public async Task<IActionResult> InvoiceList()
        {
            if (!await CheckAccessAsync(7)) 
            {
                return RedirectTo();
            }

            return View();
        }


        public async Task<IActionResult> PayInvoice(int? id, decimal? balance)
        {
            if (!await CheckAccessAsync(7))
            {
                return RedirectTo();
            }

            ViewBag.PaymentId = id;

            ViewBag.Balance = balance;

            var patientId = await _billing.patientID(id);

            ViewBag.PatientId = patientId;

           var model = await _billing.payInvoice();

            return View(model);
        }

        public async Task<IActionResult> EditInvoice(int? id)
        {
            if (!await CheckAccessAsync(7))
            {
                return RedirectTo();
            }

            ViewBag.PaymentId = id;

            var model = await _billing.payInvoice();

            return View(model);
        }


        public async Task<IActionResult> Payment(int? id, decimal? balance)
        {
            if (!await CheckAccessAsync(7))
            {
                return RedirectTo();
            }
            if (id != null)
            {
                ViewBag.PaymentId = id;

                ViewBag.Balance = balance;

                var patientId = await _billing.patientID(id);

                ViewBag.PatientId = patientId;

                return View();
            }
            else
            {
                return RedirectToAction(nameof(InvoiceList));
            }

        }

        public async Task<IActionResult> PrintInvoice(int? id)
        {
            if (!await CheckAccessAsync(7))
            {
                return RedirectTo();
            }
            var model = await _billing.PaymentVM(id);

            return View(model);
        }


        public async Task<IActionResult> GenerateInvoice(int? id)
        {
            if (!await CheckAccessAsync(7))
            {
                return RedirectTo();
            }
            ViewData["staffList"] = await selectListServices.GetAllStaffSelectListAsync();

            var model = await _billing.generateInvoiceModel(id);

            return View(model);

        }



        //LOGIC

        //WALA PA
        [HttpPost]
        public async Task<IActionResult> editPatientPayment(PatientPayments patientPayments)
        {
            if (!await CheckAccessAsync(7))
            {
                return RedirectTo();
            }
            if (patientPayments != null)
            {

                var (result, message) = await _billing.editPatientPayment(patientPayments);

                if (result)
                {
                    return RedirectToAction(nameof(InvoiceList));
                }

                return View();
            }
            else
            {
                return RedirectToAction(nameof(InvoiceList));
            }


        }



        [HttpPost]
        public async Task<IActionResult> AddPatientPayment(PatientPayments patientPayments)
        {
            if (patientPayments != null)
            {

                var (result, message) = await _billing.addPatientPayment(patientPayments);

                if (result)
                {
                    return RedirectToAction(nameof(InvoiceList));
                }

                return View();
            }
            else
            {
                return RedirectToAction(nameof(InvoiceList));
            }
   

        }
       

        [HttpPost]
        public async Task<IActionResult> AddItem(string itemName, string description, decimal price)
        {

            var (result, message) = await _billing.createItems(itemName, description, price);

            if (result)
            {
                return Json(message);
            }else
            {
                return Json(message);
            }

       
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteItem(int itemId)
        {

            var (result, message) = await _billing.deleteItem(itemId);

            if (result)
            {
                return Json(message);
            }
            else
            {
                return Json("Cant Delete Item");
            }


        }

        [HttpDelete]
        public async Task<IActionResult> DeleteService(int serviceId)
        {

            var (result, message) = await _billing.deleteService(serviceId);

            if (result)
            {
                return Json(message);
            }
            else
            {
                return Json("Cant Delete Item");
            }


        }



        [HttpPost]
        public async Task<IActionResult> EditItem(int id, string itemName, string description, decimal price)
        {

            var (result, message) = await _billing.editItems(id, itemName, description, price);

            if (result)
            {
                return Json(message);
            }
            else
            {
                return Json("Cant Update Item");
            }

        }


        [HttpPost]
        public async Task<IActionResult> EditService(int id, string serviceName, string description, decimal price)
        {

            var (result, message) = await _billing.editServices(id, serviceName, description, price);

            if (result)
            {
                return Json(message);
            }
            else
            {
                return Json("Cant Update Services");
            }

        }


        [HttpPost]
        public async Task<IActionResult> AddService(string serviceName, string description, decimal price)
        {

            var (result, message) = await _billing.createServices(serviceName, description, price);

            if (result)
            {
                return Json(message);
            }
            else
            {
                return Json("Cant Add Services");
            }


        }

        [HttpPost]
        public async Task<IActionResult> PatientSearchResult(string patientName)
        {

            var (result, list) = await _billing.searchPatient(patientName);

            if (result)
            {
                return Json(list);
            }
            else
            {
                return Json(null);
            }
        }



        
        [HttpPost]
        public async Task<IActionResult> CreateInvoice(BillingAndPrintVM billingAndPrint, string action)
        {
            if (action == "Save")
            {
                var (result, id) = await _billing.editInvoice(billingAndPrint.BillingDTO);

                if (result)
                {
                    return RedirectToAction(nameof(InvoiceList));

                }
                return RedirectToAction(nameof(Index));

            }
            else
            {
                var (result, id) = await _billing.createInvoice(billingAndPrint.BillingDTO);

                if (result)
                {
                    if (action == "MakePayment")
                    {
                        return RedirectToAction(nameof(PrintInvoice), new { id });
                    }
                    else if (action == "SaveAndPayLater")
                    {
                        return RedirectToAction(nameof(InvoiceList));
                    }
                }
                return RedirectToAction(nameof(Index));
            }
        }




        [HttpPost]
        public async Task<IActionResult> AllItems()
        {
            var allItems = await _billing.allItems();

            return Json(allItems);
        }

        [HttpPost]
        public async Task<IActionResult> AllServices()
        {
            var allServices = await _billing.allServices();

            return Json(allServices);
        }

        [HttpDelete]
        public async Task<JsonResult> DeletePayment(int paymentId)
        {
            try
            {
                if (paymentId != null)
                {

                    var (result, message) = await _billing.deleyePayment(paymentId);

                    if (result)
                    {
                        return Json(message);

                    }
                    else
                    {
                        return Json(message);
                    }
                }
                return Json(new { IsSuccess = false, Message = "Delete Payment failed!" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, $"Error occurred while deleting family planning record for Patient");
                return Json(new { IsSuccess = false, Message = "An error occurred in DeleteFPRecord." });
            }
        }

        [HttpDelete]
        public async Task<JsonResult> DeletePatientPayment(int paymentId)
        {
            try
            {
                if (paymentId != null)
                {

NatalCare_System/Views/Shared/Components/PaymentHistoryRecords/Default.cshtml
@model List<NatalCare.Models.Entities.PatientPayments>
@{
    string? patientId = ViewBag.PatientId as String;

    int? billNo = ViewBag.PaymentId as int?;
    decimal? balance = ViewBag.Balance as decimal?;

    string? name = string.Empty;

    List<decimal?> allAmount= new List<decimal?>();


    decimal? totalAmount = 0;


}


<div class="table-responsive">
    <table id="patientPaymenTable" class="table table-hover table-striped">
        <thead class="border-bottom-2">
            <tr>
                <th>Patient's Money</th>
                <th>Patient's Amount To Pay</th>
                <th>Payment Method</th>
                <th>Date Paid</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody style="text-align:center;">
            @if (Model != null && Model.Any())
            {
                foreach (var payments in Model)
                {
                    name = payments.Patients.FirstName
                    + (payments.Patients.MiddleName != null ? " " + payments.Patients.MiddleName + " " : " ")
                    + payments.Patients.LastName;

                    if (balance == 0)
                    {
                        allAmount.Add(payments.Amount);
                    }
        

                    <tr class="align-middle">

                        <td>₱ @payments.PatientsMoney</td>
                        <td>₱ @payments.Amount</td>
                        
                        <td>@payments.Payment_Method</td>
                        <td>@(payments.DatePaid?.ToString("MMMM d, yyyy") ?? "N/A")</td>
                        <td class="text-center">
                            <div class="d-flex align-items-center justify-content-center gap-2">

                                <a class="btn btn-sm btn-outline-secondary editPatientPaymentForModal" data-amount="@payments.Amount" data-paymethod="@payments.Payment_Method" data-id="@payments.PatientPaymentID" onclick="preventFormSubmit(event)" data-bs-toggle="modal" data-bs-target="#addSection">
                                    <i class="fa fa-pen"></i> EDIT
                                </a>
                                |
                                <button class="btn btn-sm btn-outline-danger dlt-pay" data-paymentid="@payments.PatientPaymentID">
                                    <i class="fa-solid fa-trash"></i> Delete
                                </button>
                            </div>
                        </td>
                    </tr>
                }
                totalAmount = allAmount.Sum(x => x ?? 0);
            }
            else
            {

                <script>
                    $(document).ready(function () {
                        $("#billTag").hide();
                        $("#nameTag").hide();
                    });
                </script>
 
            }
        </tbody>
    </table>
    @if(totalAmount != 0){
        <input type="hidden" id="totalAmount" value="@totalAmount" />

    }
</div>
@if (Model == null ){
    <script>
        $(document).ready(function () {
            $("#billTag").hide();
            $("#nameTag").hide();
        });
    </script>
}
<script>
    $(document).ready(function () {

        $('.editPatientPaymentForModal').on("click", function (e) {

            var id = $(this).data('id');

            var paymentAmount = $(this).data('amount');
            var paymentMethod = $(this).data('paymethod');

            
               
            $("#patientPaymentId").val(id);

            $("#payAmount").val(paymentAmount);
            $("#patpaymeth").val(paymentMethod);

        });


        var patientName = @Html.Raw(Json.Serialize(name));

        var billNumber = @Html.Raw(Json.Serialize(billNo));
        var balance = @Html.Raw(Json.Serialize(balance.HasValue ? balance.Value.ToString("F2") : "0.00"));


        $("#patientNameHeader").text(patientName);
        $("#patientBillNumberHeader").text(billNumber);

        $("#payInvoiceBtn").attr("href", "/Billing/PayInvoice?id=" + billNumber + "&balance=" + balance);



        // Initialize DataTables
        $('#patientPaymenTable').DataTable({
            paging: true,
            lengthChange: true,
            searching: true,
            ordering: true,
            lengthMenu: [10, 20, 50, 100],
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search Invoice...",
                paginate: {
                    previous: "Previous",
                    next: "Next"
                },
                emptyTable: "There are no Payment History"
            },
            info: true,
            autoWidth: false,
            responsive: true,
            columnDefs: [{
                "defaultContent": "-",
                "targets": "_all"
            }]
        });

        $('#patientPaymenTable').on("click", ".dlt-pay", function (e) {
            var paymentid = $(this).data('paymentid');
            DeletePatientPayment(paymentid);
        });

        // Delete Payment
        function DeletePatientPayment(paymentid) {
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this Payment!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: 'DELETE',
                        url: '@Url.Action("DeletePatientPayment", "Billing")',
                        data: { paymentId: paymentid },
                        success: function (result) {
                            
                            toastr.success(result);
                            setTimeout(function () {
                                window.location.href = '@Url.Action("InvoiceList", "Billing")';
                            }, 2000);
                        },
                        error: function () {
                            console.log('Unable to delete the patient.');
                        }
                    });
                }
            });
        }
    });
</script>