NatalCare_System/Controllers/AdmissionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NatalCare.DataAccess.Extensions;
using NatalCare.DataAccess.Interfaces;
using NatalCare.Models.Entities;

namespace NatalCare_System.Controllers
{
    [Authorize]
    public class AdmissionController : BaseController<AdmissionController>
    {
        private readonly ISelectListServices selectListServices;
        private readonly IServicesOperationServices serviceServices;
        private readonly ICountServices countservices;

        public AdmissionController(ICountServices countservices, IServicesOperationServices serviceServices, ISelectListServices selectListServices, IModuleAccessServices moduleAccessServices)
           : base(moduleAccessServices)
        {
            this.serviceServices = serviceServices;
            this.selectListServices = selectListServices;
            this.countservices = countservices;
        }
        public async Task<IActionResult> Index()
        {
            if (!await CheckAccessAsync(4)) 
            {
                return RedirectTo();
            }

            // Get all counts in one call
            var (totalAdmitted, totalInLabor, totalPospartum) = await countservices.GetAdmissionCountsAsync();
            // Pass counts to the view using ViewBag
            ViewBag.TotalAdmitted = totalAdmitted;
            ViewBag.TotalInLabor = totalInLabor;
            ViewBag.TotalPospartum = totalPospartum;


            var patients = await serviceServices.GetAllDeliveryRecords();
            return View(patients ?? new List<Delivery>());
        }

        public async Task<IActionResult> Create(string id)
        {
            if (!await CheckAccessAsync(4))
            {
                return RedirectTo();
            }
            ViewData["triggerPatID"] = id;
            ViewData["deliveryStatus"] = await selectListServices.GetDeliveryStatusSelectListAsyncExceptReferral();
            ViewData["wardList"] = await selectListServices.GetWardsSelectListAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Delivery model)
        {
            if (ModelState.IsValid)
            {
                var userId = GetCurrentUserId();
                var result = await serviceServices.AddAdmissionDelivery(model, userId);
                if (result.IsSuccess == true)
                {
                    TempData["success"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
            

        public async Task<IActionResult> Edit(string id, string patid)
        {
            if (!await CheckAccessAsync(4))
            {
                return RedirectTo();
            }
            ViewData["triggerPatID"] = patid;
            ViewData["deliveryStatus"] = await selectListServices.GetDeliveryStatusSelectListAsync();
            ViewData["wardList"] = await selectListServices.GetWardsSelectListAsync();
            var userId = GetCurrentUserId();
            var result = await serviceServices.GetAdmittedDeliveryRecord(id);
            if (result != null)
            {
                return View(result);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id, string patid)
        {
            if (!await CheckAccessAsync(4))
            {
                return RedirectTo();
            }
            ViewData["triggerPatID"] = patid;
            ViewData["deliveryStatus"] = await selectListServices.GetDeliveryStatusSelectListAsync();
            ViewData["wardList"] = await selectListServices.GetWardsSelectListAsync();
            var userId = GetCurrentUserId();
            var result = await serviceServices.GetAdmittedDeliveryRecord(id);
            if (result != null)
            {
                return View(result);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Delivery model)
        {
            if (!await CheckAccessAsync(4))
            {
                return RedirectTo();
            }

            if (ModelState.IsValid)
            {
                var userId = GetCurrentUserId();
                var result = await serviceServices.UpdateAdmissionDelivery(model, userId);
                if (result.IsSuccess == true)
                {
                    TempData["success"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }




        // HELPER 
        public async Task<JsonResult> GetBedNumber(int wardId)
        {
            var data = await selectListServices.GetBedsSelectListAsync(wardId);
            if(data == null)
            {
                return Json(new { isSuccess = false, item = "No data found!" });
            }
            return Json(new { isSuccess = true, item = data.Items });
        }

        public async Task<JsonResult> GetBedNumberorEdit(int wardId)
        {
            var data = await selectListServices.GetAllBedSelectListAsync(wardId);
            if (data == null)
            {
                return Json(new { isSuccess = false, item = "No data found!" });
            }
            return Json(new { isSuccess = true, item = data.Items });
        }



        private string GetCurrentUserId()
        {
            return User.GetUserId();
        }
    }
}

NatalCare_System/Views/Admission/Index.cshtml
@model List<NatalCare.Models.Entities.Delivery>

@{
    ViewData["Title"] = "Admission Records";
    ViewData["NavTitle"] = "Admission Records";
    Layout = "_UserLayout";
}

<!-- NAVBAR -->
<partial name="Partial/_Navbar" />

<div class="mx-4">
    <div class="row">
        <div class="col-md-3 mb-4">
            <div class="card shadow py-2 card-selected">
                <div class="card-body">
                    <div class="row">
                        <div class="col mr-2">
                            <div class="fw-bold mb-1" style="font-size: 1em; color: var(--dark);">
                                Total Admitted
                            </div>
                        </div>
                        <div class="col-auto align-items-center" style="padding-right:2rem;">
                            <div class="h1">
                                @(ViewBag.TotalAdmitted ?? 0)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3 mb-4">
            <div class="card shadow py-2 card-selected">
                <div class="card-body">
                    <div class="row">
                        <div class="col mr-2">
                            <div class="fw-bold mb-1" style="font-size: 1em; color: var(--dark);">
                                Total In-Labor
                            </div>
                        </div>
                        <div class="col-auto align-items-center" style="padding-right:2rem;">
                            <div class="h1">
                                @(ViewBag.TotalInLabor ?? 0)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3 mb-4">
            <div class="card shadow py-2 card-selected">
                <div class="card-body">
                    <div class="row">
                        <div class="col mr-2">
                            <div class="fw-bold mb-1" style="font-size: 1em; color: var(--dark);">
                                Total Pospartum Care
                            </div>  
                        </div>
                        <div class="col-auto align-items-center" style="padding-right:2rem;">
                            <div class="h1">
                                @(ViewBag.TotalPospartum ?? 0)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mb-4 mt-2 d-flex align-items-center justify-content-end gap-3">
        <a class="btn btn-pink " asp-controller="Admission" asp-action="Create">
            <i class="fas fa-plus" style="font-size: 18px;"></i>
            <strong>Add Admit Patient</strong>
        </a>
    </div>

    <div class="card shadow-sm card-selected">
        <div class="card-body">
            <div class="table-responsive">
                <table id="newbornTable" class="table table-hover table-striped table-datatable">
                    <thead class="border-bottom-2">
                        <tr>
                            <th>Profile</th>
                            <th>Patient No#</th>
                            <th>Patient Name</th>
                            <th>Date & Time Admitted</th>
                            <th>Date & Time Discharge</th>
                            <th>Ward No#</th>
                            <th>Bed No#</th>
                            <th>Patient Status</th>
                            <th>Notes</th>
                            <th>Added By</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="~/profile/@(item.Patient?.Gender?.ToLower() == "female" ? "woman.png" : "man.png")"
                                         width="50" height="50" alt="Profile" class="img-fluid rounded-circle" />
                                </td>
                                <th>@item.PatientID</th>
                                <td>@item.Patient?.FirstName @item.Patient?.MiddleName @item.Patient?.LastName</td>
                                <td>@item.Date_Admitted.ToString("MMM dd yyyy") @item.Time_Admitted</td>
                                <td>@item.Date_Discharged @item.Time_Discharged</td>
                                <td>@item.Wards?.WardNo</td>
                                <td>@item.Beds?.BedNo</td>
                                <td>
                                    @if (item.DeliveryStatusID == 1)
                                    {   //In Labor
                                        <span class="badge bg-success">@item.DeliveryStatus?.StatusName</span>
                                    }
                                    else if (item.DeliveryStatusID == 2)
                                    {   //PostPartum
                                        <span class="badge bg-warning">@item.DeliveryStatus?.StatusName</span>
                                    }
                                    else if (item.DeliveryStatusID == 3)
                                    {   // Discharged
                                        <span class="badge bg-danger">@item.DeliveryStatus?.StatusName</span>
                                    }
                                    else if (item.DeliveryStatusID == 4)
                                    {   // Reffered
                                        <span class="badge bg-info text-dark">@item.DeliveryStatus?.StatusName</span>
                                    }
                                </td>
                                <td>@item.Notes</td>
                                <td>@item.CreatedBy?.FirstName @item.CreatedBy?.MiddleName @item.CreatedBy?.LastName</td>
                                <td>
                                    <div class="d-flex align-items-center justify-content-center gap-2">
                                        <a class="btn btn-outline-secondary medical-records-link" asp-controller="Patient" asp-action="MedicalRecords" asp-route-id="@item.PatientID">
                                            <i class="fa-solid fa-list"></i>
                                        </a>
                                        <a class="btn btn-outline-primary" asp-controller="Admission" asp-action="Edit" asp-route-id="@item.CaseNo">
                                            <i class="fa-solid fa-pencil"></i>
                                        </a>
                                       @*  <button class="btn btn-outline-danger dlt-Btn">
                                            <i class="fa-solid fa-trash"></i>
                                        </button> *@
                                    </div>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>



<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Attach a click event to the medical records link
        document.querySelectorAll('.medical-records-link').forEach(function (link) {
            link.addEventListener('click', function () {
                // Directly activate the "Delivery" tab
                localStorage.setItem('activeTab', '#delivery');
            });
        });
    });
</script>

NatalCare_System/Views/Admission/Information.cshtml
@{
    ViewData["Title"] = "Admission";
    ViewData["NavTitle"] = "Admission / Patient Information";
    Layout = "_UserLayout";
}

<!-- NAVBAR -->
<partial name="Partial/_Navbar" />

<div class="mx-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card mb-4 position-relative">
                <div class="b-left"></div>
                <div class="card-body">
                    <div class="d-flex align-items-center gap-3">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            Patient Name:
                        </div>
                        <div class="h4 fw-bold mb-0">
                            Jennelyn Pepito
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 position-relative">
                <div class="b-left"></div>
                <div class="card-body">
                    <div class="d-flex align-items-center gap-3">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            Patient ID:
                        </div>
                        <div class="h4 fw-bold mb-0">
                            P-101
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="d-flex justify-content-end mb-3">
            <a asp-controller="" asp-action="" class="btn btn-pink">
                <i class="fas fa-plus"></i>
                <span>Add Services</span>
            </a>
        </div>

        <div class="col-md-3 mb-4">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="card-title m-0">Details</h5>
                    <div class="d-flex align-items-center gap-4">
                        <a class="text-dark" href="#">
                            <i class="fa-solid fa-list" style="font-size: 20px;"></i>
                        </a>
                        <a class="text-success" href="#">
                            <i class="fa-solid fa-pen-to-square" style="font-size: 20px;"></i>
                        </a>
                    </div>
                </div>

                <div class="card-body c-details">
                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            Address:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            Talamban, Cebu
                        </div>
                    </div>

                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            Age:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            24
                        </div>
                    </div>

                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            Gender:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            Female
                        </div>
                    </div>
                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            BIRTHDATE:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            06/10/2002
                        </div>
                    </div>
                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            PHONE NUMBER:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            09561552753
                        </div>
                    </div>
                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            CIVIL STATUS:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            Married
                        </div>
                    </div>
                    <div class="d-flex flex-column mb-4">
                        <div class="fw-bold text-uppercase" style="font-size: .7em;">
                            OCCUPATION:
                        </div>
                        <div class="h5 fw-bold mb-0">
                            Housewife
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-9 mb-4">
            <div class="card mb-5">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="card-title m-0">Admission</h5>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-datatable">
                            <thead>
                                <tr>
                                    <th>Admission No#</th>
                                    <th>Services</th>
                                    <th>Date Admitted</th>
                                    <th>Date Discharge</th>
                                    <th>Ward Number</th>
                                    <th>Notes</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>ADO01</td>
                                    <td>Delivery</td>
                                    <td>10/10/2024</td>
                                    <td>10/11/2024</td>
                                    <td>Ward 1</td>
                                    <td>Test</td>
                                    <td>
                                        <div class="d-flex align-items-center justify-content-center gap-4">
                                            <a class="text-dark" href="#">
                                                <i class="fa-solid fa-list" style="font-size: 24px;"></i>
                                            </a>

                                            <a class="text-success" href="#">
                                                <i class="fa-solid fa-pen-to-square" style="font-size: 24px;"></i>
                                            </a>

                                            <a class="text-danger" href="#">
                                                <i class="fa-solid fa-trash-can" style="font-size: 24px;"></i>
                                            </a>

                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>