NatalCare_System/Controllers/PrintController.cs
using Microsoft.AspNetCore.Mvc;
using NatalCare.DataAccess.Interfaces;
using NatalCare.Models.Entities;
using NatalCare.Models.ViewModel.Patient;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace NatalCare_System.Controllers
{
    public class PrintController : BaseController<PrintController>
    {
        private readonly IPatientServices patientServices;
        private readonly INewbornServices newbornServices;
        private readonly IServicesOperationServices serviceServices;

        public PrintController(IPatientServices patientServices, INewbornServices newbornServices, IServicesOperationServices serviceServices, IModuleAccessServices moduleAccessServices) : base(moduleAccessServices)
        {
            this.patientServices = patientServices;
                       this.newbornServices = newbornServices;
            this.serviceServices = serviceServices;
        }

        //Print Patient 
        public async Task<IActionResult> PrintPatientForm(string id)
        {
            try
            {
                var response = await patientServices.GetInformation(id);
                if (response.PatientID != null)
                {
                    return Json(new { IsSuccess = true, PatientId = response.PatientID });
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrintPatientForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Patient_Form(string id)
        {
            try
            {
                var response = await patientServices.GetInformation(id);
                if (response.PatientID != null)
                {
                    return View(response);
                }
                return NotFound(response);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in Patient_Form action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }

        }

        //Print Newborn
        public async Task<IActionResult> PrintNewbornForm(string id)
        {
            try
            {
                var response = await newbornServices.GetInformation(id);
                if (response.Item != null)
                {
                    return Json(new { IsSuccess = true, Newborn = response.Item });
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrintNewbornForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Newborn_Form(string id)
        {
            try
            {
                var response = await newbornServices.GetInformation(id);
                if (response.Item != null)
                {
                    return View(response.Item);
                }
                return NotFound(response);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in Patient_Form action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }

        }


        //Print Prenatal
        public async Task<IActionResult> PrintPrenatalForm(string id)
        {
            try
            {
                var response = await serviceServices.GetPrenatalInformation(id);
                if (response.CaseNo != null)
                {
                    return Json(new { IsSuccess = true, caseNo = response.CaseNo, patientId = response.PatientID});
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrintPrenatalForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Prenatal_Form(string id, string patientId)
        {
            try
            {
                var prenatal = await serviceServices.GetPrenatalInformation(id);
                var prenatalVisit = await serviceServices.GetPrenatalVisitsRecords(id, patientId);
                if (prenatal.CaseNo != null)
                {
                    var viewModel = new PrenatalVM
                    {
                        Prenatal = prenatal,
                        PrenatalVisit = prenatalVisit
                    };
                    return View(viewModel);
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in Screening_Form action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }

        //Print Hearing
        public async Task<IActionResult> PrintHearingForm(string id)
        {
            try
            {
                var response = await serviceServices.GetHRRecordAsync(id);
                if (response.Item != null)
                {
                    return Json(new { IsSuccess = true, data = response.Item });
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrintHearingForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Hearing_Form(string id)
        {
            try
            {
                var response = await serviceServices.GetHRFormPrint(id);
                if (response.Item != null)
                {
                    return View(response.Item);
                }
                return NotFound(response);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in Patient_Form action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }

        //Print Screening
        public async Task<IActionResult> PrintScreeningForm(string id)
        {
            try
            {
                var response = await serviceServices.GetScreeningFormPrint(id);
                if (response.Item != null)
                {
                    return Json(new { IsSuccess = true, data = response.Item });
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrinScreeningForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Screening_Form(string id)
        {
            try
            {
                var response = await serviceServices.GetScreeningFormPrint(id);
                if (response.Item != null)
                {
                    return View(response.Item);
                }
                return NotFound(response);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in Screening_Form action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }


        //Print Dischargement
        public async Task<IActionResult> PrintDichargementForm(int id)
        {
            try
            {
                var response = await serviceServices.GetDFPrintForm(id);
                if (response.Id > 0)
                {
                    return Json(new { IsSuccess = true, dichargementId = response.Id });
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrintDichargementForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Dischargement_Form(int id)
        {
            try
            {
                var response = await serviceServices.GetDFPrintForm(id);
                if (response.Id > 0)
                {
                    return View(response);
                }
                return NotFound(response);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in Screening_Form action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }



        //Print Physical Examination
        public async Task<IActionResult> PrintPEForm(int id)
        {
            try
            {
                var response = await serviceServices.GetPhysicalExaminationRecord(id);
                if (response.Item != null)
                {
                    return Json(new { IsSuccess = true, data = response.Item });
                }
                return Json(new { IsSuccess = false, Message = "There is an error, Ask the It support" });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error in PrintPEForm action");
                return Json(new { IsSuccess = false, Message = "There is an error!" });
            }
        }
        public async Task<IActionResult> Examination_Form(int id)

NatalCare_System/Views/Reports/Invoices.cshtml
@{
    ViewData["Title"] = "Invoices Reports";
    ViewData["NavTitle"] = "Invoices Reports";
    Layout = "_UserLayout";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-tooltip"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
<script src="~/lib/jquery/dist/jquery.min.js"></script>

<partial name="Partial/_Navbar" />

<div class="mx-4">
    <div class="card shadow-sm card-selected">
        <div class="card-body" id="paymentReports">

            <div class="row">
                <div class="col-md-6">
                    <canvas id="myChart" style="width:100%;max-width:600px"></canvas>
                </div>
                <div class="col-md-6">
                    <canvas id="myChart1" style="width:100%;max-width:600px"></canvas>

                </div>
            </div>


        </div>
    </div>
</div>
<script src="~/js/admin/paymentReports.js"></script>

NatalCare_System/Views/Reports/Natality.cshtml
@{
    ViewData["Title"] = "Natality Reports";
    ViewData["NavTitle"] = "Natality Reports";
    Layout = "_UserLayout";
}

<!-- NAVBAR -->
<partial name="Partial/_Navbar" />

<div class="mx-4">
    <div class="row">
        <div class="col-md-4 mb-sm-3">
            <!-- Delivery Type Distribution (Doughnut Graph) -->
            <div class="card h-100 p-3">
                <h6 class="card-title">Delivery Type Distribution</h6>
                <canvas id="doughnutGraph"></canvas>
            </div>
        </div>
        <div class="col-md-4 mb-sm-3">
            @* Deliveries Attended by Skilled Health Professionals (Pie Graph) *@
            <div class="card h-100 p-3">
                <h6 class="card-title">Deliveries Attended by Skilled Health Professionals</h6>
                <canvas id="pieGraph"></canvas>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card p-3 mb-4">
                <h6 class="card-title">Generate Natality Reports</h6>
                <div class="d-flex align-items-center justify-content-end gap-3">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#NatalReportModal">
                        <i class="fas fa-file-pdf"></i>
                        Generate
                    </button>
                </div>
            </div>

            <div class="card p-3 mb-4">
                <h6 class="card-title">Generate Patient List Reports</h6>
                <div class="d-flex align-items-center justify-content-end gap-3">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#NatalReportModal">
                        <i class="fas fa-file-pdf"></i>
                        Generate
                    </button>
                </div>
            </div>

            <div class="card p-3 mb-4">
                <h6 class="card-title">Generate Newborn List Reports</h6>
                <div class="d-flex align-items-center justify-content-end gap-3">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#NatalReportModal">
                        <i class="fas fa-file-pdf"></i>
                        Generate
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Newborn Modal -->
<div class="modal fade" id="NewbornReportModal" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header bg-pink">
                <h5 class="modal-title">Start Date and End Date</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-controller="Reports" asp-action="NewbornReport">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="startDate" class="control-label">Start Date</label>
                            <input type="date" id="startDate" name="startDate" class="form-control" required />
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="endDate" class="control-label">End Date</label>
                            <input type="date" id="endDate" name="endDate" class="form-control" required />
                        </div>

                        <div class="col-12 mt-3 d-flex justify-content-end">
                            <div class="d-flex align-items-center gap-3">
                                @*  <button class="btn btn-danger generateNatalPdfBtn" disabled >
                                    <i class="fas fa-file-pdf"></i>
                                    PDF
                                </button> *@
                                <button type="submit" class="btn btn-success generateNatalBtn">
                                    <i class="fas fa-file-excel"></i>
                                    Generate
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Patient Modal -->
<div class="modal fade" id="PatientReportModal" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header bg-pink">
                <h5 class="modal-title">Start Date and End Date</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-controller="Reports" asp-action="PatientReport">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="startDate" class="control-label">Start Date</label>
                            <input type="date" id="startDate" name="startDate" class="form-control" required />
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="endDate" class="control-label">End Date</label>
                            <input type="date" id="endDate" name="endDate" class="form-control" required />
                        </div>

                        <div class="col-12 mt-3 d-flex justify-content-end">
                            <div class="d-flex align-items-center gap-3">
                                @*  <button class="btn btn-danger generateNatalPdfBtn" disabled >
                                    <i class="fas fa-file-pdf"></i>
                                    PDF
                                </button> *@
                                <button type="submit" class="btn btn-success generateNatalBtn">
                                    <i class="fas fa-file-excel"></i>
                                    Excel
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Natality Modal -->
<div class="modal fade" id="NatalReportModal" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header bg-pink">
                <h5 class="modal-title">Start Date and End Date</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-controller="Reports" asp-action="NatalityReport">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="startDate" class="control-label">Start Date</label>
                            <input type="date" id="startDate" name="startDate" class="form-control" required />
                        </div>

                        <div class="col-md-6 mb-3">
                            <label for="endDate" class="control-label">End Date</label>
                            <input type="date" id="endDate" name="endDate" class="form-control" required />
                        </div>

                        <div class="col-12 mt-3 d-flex justify-content-end">
                            <div class="d-flex align-items-center gap-3">
                               @*  <button class="btn btn-danger generateNatalPdfBtn" disabled >
                                    <i class="fas fa-file-pdf"></i>
                                    PDF
                                </button> *@
                                <button type="submit" class="btn btn-success generateNatalBtn" >
                                    <i class="fas fa-file-excel"></i>
                                    Generate
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<!-- Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Delivery Types (Doughnut Chart)
        const deliveryData = {
            labels: ['Cesarean', 'Vaginal'],
            datasets: [{
                label: 'Delivery Type Statistics',
                data: [80, 120], // Example data: 80 Cesarean, 120 Vaginal
                backgroundColor: [
                    'rgba(255, 99, 132, 0.7)', // Cesarean
                    'rgba(54, 162, 235, 0.7)'  // Vaginal
                ],
                hoverOffset: 4
            }]
        };
        const deliveryConfig = {
            type: 'doughnut',
            data: deliveryData,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: false,
                        text: 'Delivery Type Distribution'
                    }
                }
            }
        };
        new Chart(document.getElementById('doughnutGraph'), deliveryConfig);

        // Skilled Health Professionals (Pie Chart)
        const skilledData = {
            labels: ['Physician', 'Nurse', 'Midwife'],
            datasets: [{
                label: 'Skilled Health Professionals',
                data: [60, 40, 100], // Example data
                backgroundColor: [
                    'rgba(75, 192, 192, 0.7)', // Physician
                    'rgba(153, 102, 255, 0.7)', // Nurse
                    'rgba(255, 159, 64, 0.7)'   // Midwife
                ],
                hoverOffset: 4
            }]
        };
        const skilledConfig = {
            type: 'pie',
            data: skilledData,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: false,
                        text: 'Deliveries Attended by Skilled Health Professionals'
                    }
                }
            }
        };
        new Chart(document.getElementById('pieGraph'), skilledConfig);

    });

</script>

NatalCare_System/Views/Reports/NatalityReport.cshtml
@using NatalCare.Models.ViewModel.Patient
@model NatalityReportVM

@{
    ViewData["Title"] = "Natality Reports";
    ViewData["NavTitle"] = "Natality Reports";
    Layout = "_UserLayout";
}

<partial name="Partial/_Navbar" />

<div class="mx-4">
    <div class="d-flex align-items-center justify-content-start gap-3 mb-3">
        <a asp-controller="Reports" asp-action="Natality" class="btn btn-sm btn-outline-pink">
            <i class="fas fa-arrow-left"></i>
            <span>Back</span>
        </a>
    </div>          
    <div class="card shadow-sm card-selected">
        <div class="card-body">
            <h5 class="text-center fst-italic pt-2">Natality Reports</h5>
            <div class="d-flex justify-content-end mb-3">
                <a asp-controller="Print" asp-action="Natality_Form" asp-route-startDate="@ViewBag.startDate" asp-route-endDate="@ViewBag.endDate" class="btn btn-success">
                    <i class="fas fa-save"></i>
                    <span>Print</span>
                </a>
            </div>

            <div class="container-sm">
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead>
                            <tr>
                                <th rowspan="2">INDICATORS</th>
                                <th colspan="6">AGES</th>
                                <th rowspan="2">Total Number</th>
                            </tr>
                            <tr>
                                <th colspan="2">10-14</th>
                                <th colspan="2">15-19</th>
                                <th colspan="2">20-49</th>
                            </tr>
                            <tr>
                                <th>1. Number Of Deliveries</th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
                                <th>M</th>
                                <th>F</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>2. Total No. of Live Births</th>
                                <td>@Model.Male_10_14</td>
                                <td>@Model.Female_10_14</td>
                                <td>@Model.Male_15_19</td>
                                <td>@Model.Female_15_19</td>
                                <td>@Model.Male_20_49</td>
                                <td>@Model.Female_20_49</td>
                                <td>@Model.TotalLiveBirths</td>
                            </tr>
                            <tr>
                                <th colspan="8" class="text-start">3. Type of Delivery:</th>
                            </tr>
                            <tr>
                                <td>a. Total No. Vaginal Deliveries</td>
                                <td>@Model.VaginalMale_10_14</td>
                                <td>@Model.VaginalFemale_10_14</td>
                                <td>@Model.VaginalMale_15_19</td>
                                <td>@Model.VaginalFemale_15_19</td>
                                <td>@Model.VaginalMale_20_49</td>
                                <td>@Model.VaginalFemale_20_49</td>
                                <td>@Model.VaginalDeliveries</td>
                            </tr>
                            <tr>
                                <td>b. Total No. CS Deliveries</td>
                                <td>@Model.CSMale_10_14</td>
                                <td>@Model.CSFemale_10_14</td>
                                <td>@Model.CSMale_15_19</td>
                                <td>@Model.CSFemale_15_19</td>
                                <td>@Model.CSMale_20_49</td>
                                <td>@Model.CSFemale_20_49</td>
                                <td>@Model.CSDeliveries</td>
                            </tr>
                            <tr>
                                <th colspan="8" class="text-start">4. Number of Deliveries Attended by Skilled Health Professionals:</th>
                            </tr>
                            <tr>
                                <td>a. Physicians</td>
                                <td>@Model.PSMale_10_14</td>
                                <td>@Model.PSFemale_10_14</td>
                                <td>@Model.PSMale_15_19</td>
                                <td>@Model.PSFemale_15_19</td>
                                <td>@Model.PSMale_20_49</td>
                                <td>@Model.PSFemale_20_49</td>
                                <td>@Model.AttendedByPhysicians</td>
                            </tr>
                            <tr>
                                <td>b. Nurses</td>
                                <td>@Model.NurseMale_10_14</td>
                                <td>@Model.NurseFemale_10_14</td>
                                <td>@Model.NurseMale_15_19</td>
                                <td>@Model.NurseFemale_15_19</td>
                                <td>@Model.NurseMale_20_49</td>
                                <td>@Model.NurseFemale_20_49</td>
                                <td>@Model.AttendedByNurses</td>
                            </tr>
                            <tr>
                                <td>c. Midwives</td>
                                <td>@Model.MWMale_10_14</td>
                                <td>@Model.MWFemale_10_14</td>
                                <td>@Model.MWMale_15_19</td>
                                <td>@Model.MWFemale_15_19</td>
                                <td>@Model.MWMale_20_49</td>
                                <td>@Model.MWFemale_20_49</td>
                                <td>@Model.AttendedByMidwives</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>